---
- name: DÃ©ploiement du VNF Web Server
  hosts: localhost
  tasks:
    - name: Supprimer le conteneur existant 
      command: docker rm -f vnf-web
      ignore_errors: yes
    - name: Lancer le conteneur Web Server
      command: docker run -d --name vnf-web --network net-chain -p 8081:80 nginx
